package components.entityComponents;

public enum ComponentType {
	Label(), 
	Location(),
	Sprite(),
	Velocity(),
	ImageProperties(),
	Health(), 
	Acceleration(),
	KeyInput(),
	Splash(),
	Background(),
	Strength(),
	MonsterAction(),
	Level(),
	Step(),
	CollisionSide(), 
	GameTitle(),
	GameInstructions(),
	Duration(),
	Lives(),
	Score(),
	Type(), 
	Collidable(),
	CollisionHandler(),
	ObjectCreation(),
	Goal(),
	MonsterMovementStep(),
	Friction(),
	TerminalVelocity;
}
