package view_interfaces;

/**
 * View for the playing version of the front end. Will be the controller for everything for the front
 * end from handling button presses, to moving the game objects.
 * @author Henry
 *
 */

public interface UIViewInterface {

	/**
	 * Add a UI image with the correct location based off of the XML file generated by the Game Authors
	 * @param picturePath - file path to picture for object
	 * @param x - x location
	 * @param y - y location
	 * @param width - height of character
	 * @param height - width of character
	 */
	public void addUIImage(String picturePath, double x, double y, double width, double height);
	
	/**
	 * Starts the animation to run the game
	 */
	public void runGame();
}
